[variables]
COMPOSER_MEMORY_LIMIT = "-1"

[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nginx"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
    "composer install --no-interaction --no-scripts --prefer-dist"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "php artisan package:discover --ansi"
]
