[variables]
COMPOSER_MEMORY_LIMIT = "-1"
APP_KEY = "base64:YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE="
APP_ENV = "production"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/tmp/build.sqlite"

[phases.install]
dependsOn = ["setup"]
cmds = [
    "composer install --ignore-platform-reqs --no-interaction --no-scripts --prefer-dist --no-dev"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "cp .env.example .env",
    "php artisan package:discover --ansi"
]
